spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investing_db
    username: root
    password: 1234


  security:
    user:
      name: root
      password: 1234
  jpa:
    properties:
      hibernate:
        #show_sql: true
        #use_sql_comments: true
        #format_sql: true
        jdbc:
          batch_size: 30
          cachePrepStmts: true
          useServerPrepStmts: true
          rewriteBatchedStatements: true


#?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Istanbul

#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update

#logging:
#  level:
#    org.springframework: debug
